const explicit = new Set(['accenture','adecco','allegis group','cognizant','deloitte','ey','ernst young','hcl technologies','infosys','kforce','kpmg','manpowergroup','mckinsey company','randstad','robert half','tata consultancy services','tcs','teksystems','wipro','capgemini','bain company','boston consulting group','bcg','pwc','pricewaterhousecoopers','rsm us','slalom','thoughtworks','insight global','apex systems','motion recruitment','diverse lynx','cybercoders','jobot']);
// Defense primes and government/defense contractors (Prudhvi: direct-hire,
// no defense or government organizations). Universities are kept on purpose
// (cap-exempt employers are a priority lane).
const defense = new Set(['lockheed martin','raytheon','rtx','northrop grumman','general dynamics','bae systems','booz allen hamilton','booz allen','leidos','saic','caci','mantech','peraton','l3harris','l3 harris','harris corporation','textron','huntington ingalls','huntington ingalls industries','aerojet rocketdyne','kratos defense','kratos defense security solutions','mercury systems','draper laboratory','mitre','mitre corporation','aerospace corporation','jacobs engineering','amentum','parsons corporation','kbr','fluor corporation','v2x','bwxt','general atomics','sierra nevada corporation','anduril','anduril industries','palantir technologies','palantir','shield ai']);
const suffix = /(?:^|[\s,.-])(?:staffing|recruitment|recruiting|recruiters|talent acquisition|placement agency|employment agency|temporary help|executive search|consulting|consultants|consultancy|consultancies)(?:$|[\s,.-])/i;
const govOrg = /^(u\.s\.|us|united states)\s+(department|army|navy|air force|space force|marine corps|coast guard|government|federal)\b|^nasa$|\bdepartment of (defense|veterans affairs|homeland security|energy|state|the treasury|justice|agriculture|commerce|transportation|health and human services|education|labor|the interior|housing and urban development)\b|\b(federal bureau of investigation|federal aviation administration|environmental protection agency|food and drug administration|national institutes of health|national science foundation|national aeronautics and space administration|internal revenue service|social security administration|centers for disease control|federal reserve bank|defense logistics agency|defense information systems agency|national security agency|central intelligence agency)\b|\.gov$/i;
export function excludedEmployer(name) {
  const raw = String(name || '');
  const normalized = raw.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  return explicit.has(normalized) || defense.has(normalized) || suffix.test(raw) || govOrg.test(raw);
}
